service: konecta-backend

frameworkVersion: "3"

useDotenv: true

plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs16.x
  region: us-west-2
  environment:
    RDS_HOST: ${env:RDS_HOST}
    RDS_USER: ${env:RDS_USER}
    RDS_PASSWORD: ${env:RDS_PASSWORD}
    RDS_DATABASE: ${env:RDS_DATABASE}
    RDS_PORT: ${env:RDS_PORT}

functions:
  getTenants:
    handler: tenant/getTenants.handler
    description: Get all tenants
    events:
      - http:
          path: tenants
          method: get
          
  getTenant:
    handler: tenant/getTenant.handler
    description: Get a tenant
    events:
      - http:
          path: tenants/tenant
          method: get

  deleteTenant:
    handler: tenant/deleteTenant.handler
    description: Delete tenant
    events:
      - http:
          path: tenants/tenant
          method: delete

  createTenant:
    handler: tenant/createTenant.handler
    description: Create tenant
    events:
      - http:
          path: tenants
          method: post