service: konecta-backend

frameworkVersion: "3"

useDotenv: true

plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs16.x
  region: us-west-2
  environment:
    RDS_HOST: ${env:RDS_HOST}
    RDS_USER: ${env:RDS_USER}
    RDS_PASSWORD: ${env:RDS_PASSWORD}
    RDS_DATABASE: ${env:RDS_DATABASE}
    RDS_PORT: ${env:RDS_PORT}
    STRIPE_KEY: ${env:STRIPE_KEY}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:us-west-2:424461409538"

functions:
  getTenants:
    handler: tenant/getTenants.handler
    description: Get all tenants
    events:
      - http:
          path: tenants
          method: get

  getTenant:
    handler: tenant/getTenant.handler
    description: Get a tenant
    events:
      - http:
          path: tenants/tenant
          method: get

  deleteTenant:
    handler: tenant/deleteTenant.handler
    description: Delete tenant
    events:
      - http:
          path: tenants/tenant
          method: delete

  createTenant:
    handler: tenant/createTenant.handler
    description: Create tenant
    events:
      - http:
          path: tenants
          method: post

  getProduct:
    handler: product/getProduct.handler
    description: Get an specific product from a tenant
    events:
      - http:
          path: products/product
          method: get

  getProducts:
    handler: product/getProducts.handler
    description: Get all products from a tenant
    events:
      - http:
          path: products
          method: get

  deleteProduct:
    handler: product/deleteProduct.handler
    description: Delete product from a tenant
    events:
      - http:
          path: products/product
          method: delete

  createProduct:
    handler: product/createProduct.handler
    description: Add product from a tenant
    events:
      - http:
          path: products
          method: post

  checkout:
    handler: checkout/createCheckout.handler
    description: Create checkout session from stripe
    events:
      - http:
          path: checkout
          method: post
